### ISSUE TITLE
Great Code! quick question

### ISSUE THREAD

**Issue by estoylive** [aehenao/instagramx#1]
Sorry to bother you but could you explain to me how to use this inside a node express endpoint?

i can see that editing test.ts and when executing npm run build you then modify dist/test.js and that is it. My skills are poor with node i am just starting. 

So, how would I go if I want to import your library into a node express project?

awesome work man, give us a wallet to transfer some USDC in gratitude!

**Comment by estoylive** [comment]
also i am trying to get the number of followers of a bunch of Instagram users but I keep getting nothing from some of the users. at first I thought it could be because the profiles where private but then I saw some of the profiles and they are not private at all. How would you go in order to get the numbers of followers of a given array of users (["user1", "user2", "userN"]?

**Comment by aehenao** [comment]
Hello, thanks for using my library, I have noticed that it is not extracting the followers. I'll fix it and let you know as soon as I have it.

**Comment by aehenao** [comment]
I don't have time to maintain this library.
